### Números complejos

In [1]:
1+im

1 + 1im

In [2]:
typeof(ans)

Complex{Int64}

In [3]:
0.1+im

0.1 + 1.0im

In [4]:
typeof(ans)

Complex{Float64}

In [5]:
π*im

0.0 + 3.141592653589793im

In [6]:
typeof(ans)

Complex{Float64}

# Representación de los números en la maquina

$\beta=\alpha_2 2^2+\alpha_1 2^1+\alpha_0 2^0$

In [8]:
bits(2)

"0000000000000000000000000000000000000000000000000000000000000010"

In [7]:
typeof(2)

Int64

In [9]:
bits(2.0)

"0100000000000000000000000000000000000000000000000000000000000000"

In [10]:
typeof(2.0)

Float64

In [11]:
typeof(pi)

Irrational{:π}

In [13]:
using SpecialFunctions

INFO: Precompiling module SpecialFunctions.


In [14]:
zeta(10)

1.0009945751278184

## Precisión extendida

In [15]:
BigFloat("3.14")

3.140000000000000000000000000000000000000000000000000000000000000000000000000008

In [16]:
BigFloat("2.0001")

2.000100000000000000000000000000000000000000000000000000000000000000000000000000

In [17]:
typeof(ans)

BigFloat

# Vectores y matrices y otras estructuras

In [18]:
a = [3, 2.0, 1.0]

3-element Array{Float64,1}:
 3.0
 2.0
 1.0

In [19]:
typeof(a)

Array{Float64,1}

In [20]:
a = ["foo", "bar", 10]

3-element Array{Any,1}:
   "foo"
   "bar"
 10     

In [21]:
typeof(a)

Array{Any,1}

In [22]:
zeros(10)

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

Matriz en ceros

In [23]:
ze=zeros(2,3)

2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

Creando vectores en ceros especificando el tipo.

In [24]:
zeros(Int8,10)

10-element Array{Int8,1}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

Matriz identidad

In [26]:
iden=eye(Int8,3)

3×3 Array{Int8,2}:
 1  0  0
 0  1  0
 0  0  1

In [27]:
size(ans)

(3, 3)

In [28]:
iden[1,2]

0

In [29]:
iden[1,1]

1

In [30]:
iden[0,0]

LoadError: BoundsError: attempt to access 3×3 Array{Int8,2} at index [0, 0]

In [31]:
iden[1]

1

In [33]:
iden

3×3 Array{Int8,2}:
 1  0  0
 0  1  0
 0  0  1

In [34]:
iden[5]

1

Julia comienza a contar desde el 1, cosa que es poco usual en los lenguajes de programación comunes.

Otra forma de crear matrices:

In [35]:
[1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

Covectores:

In [38]:
[1 2 3 4]

1×4 Array{Int64,2}:
 1  2  3  4

vectores

In [39]:
transpose(ans)

4×1 Array{Int64,2}:
 1
 2
 3
 4

In [40]:
typeof(ans)

Array{Int64,2}

In [41]:
[1,2,3,4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [42]:
typeof(ans)

Array{Int64,1}

In [43]:
transpose([1,2,3,4])

1×4 RowVector{Int64,Array{Int64,1}}:
 1  2  3  4

In [44]:
transpose(ans)

4-element Array{Int64,1}:
 1
 2
 3
 4

__Creación de vectores en blanco__

Si queremos por ejemplo un vector de enteros sin especificar las entradas, pero con dimensión fija, podemos hacer:

In [45]:
array = Array{Int64}(5)

5-element Array{Int64,1}:
 140082964198320
 140082964198416
 140082964198512
 140082964198832
 140082964198128

Observen que Julia lo rellena con numeros aleatorios.

La función linspace:

In [46]:
x=linspace(0.0,1.0,100);

In [49]:
x[100]

1.0

In [52]:
typeof(x)

StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}

In [53]:
rango=range(1,5)

1:5

In [59]:
1:5

1:5

In [55]:
rango[1]

1

Cfis2017#1 Cfis2017#2

# Instalando paqueterias

In [56]:
Pkg.update() # Actualiza la lista de paquetes de Julia.

INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove


In [57]:
Pkg.add("PyPlot") # mas adelante lo usaremos, mientras tanto podemos llamarlo:

INFO: Cloning cache of ColorTypes from https://github.com/JuliaGraphics/ColorTypes.jl.git
INFO: Cloning cache of Colors from https://github.com/JuliaGraphics/Colors.jl.git
INFO: Cloning cache of FixedPointNumbers from https://github.com/JuliaMath/FixedPointNumbers.jl.git
INFO: Cloning cache of LaTeXStrings from https://github.com/stevengj/LaTeXStrings.jl.git
INFO: Cloning cache of PyPlot from https://github.com/JuliaPy/PyPlot.jl.git
INFO: Cloning cache of Reexport from https://github.com/simonster/Reexport.jl.git
INFO: Installing ColorTypes v0.6.0
INFO: Installing Colors v0.8.0
INFO: Installing FixedPointNumbers v0.4.0
INFO: Installing LaTeXStrings v0.2.1
INFO: Installing PyPlot v2.3.2
INFO: Installing Reexport v0.0.3
INFO: Building Conda
INFO: Building PyCall
INFO: PyCall is using /usr/bin/python (Python 2.7.12) at /usr/bin/python, libpython = libpython2.7
INFO: /home/juser/.julia/v0.6/PyCall/deps/deps.jl has been updated
INFO: /home/juser/.julia/v0.6/PyCall/deps/PYTHON has not change

In [58]:
using PyPlot # Justo despues de instalarlo la primera vez, julia tiene que compilarlo.

INFO: Precompiling module PyPlot.


# Esturcturas basicas

## bucles y expresiones condicionales

In [60]:
# for simple
for i in -1:3
    println(i)
end

-1
0
1
2
3


In [61]:
typeof(-1:3)

UnitRange{Int64}

In [62]:
i # i es una variable local

LoadError: UndefVarError: i not defined

In [69]:
for i in 1:3
    r = i
    println(r)
end

1
2
3


In [66]:
r # esta es local también, esta dentro del for

LoadError: UndefVarError: r not defined

In [70]:
r = 0
for i in 1:2:10
    r = i
    println(r)
end

1
3
5
7
9


In [71]:
r #Aqui ya no es local, está definida como global, pues se definió fuera del bucle.

9

In [72]:
for ib = (true, false)
    for jb = (true,false)
        println( "$ib & $jb = ", ib & jb)
        println( "$ib | $jb = ", ib | jb)
    end
end

true & true = true
true | true = true
true & false = false
true | false = true
false & true = false
false | true = true
false & false = false
false | false = false


* While

In [74]:
i=0;
while i <= 5
         println(i)
         i += 1
end

0
1
2
3
4
5


* If

In [75]:
y=5;
x=6;
if x < y
  println("x is less than y")
elseif x > y
  println("x is greater than y")
else
  println("x is equal to y")
end

x is greater than y


## Creacion de funciones

In [76]:
# Calculo del volumen de una esfera de radio r
function sphere_vol(r)
    return 4/3*pi*r^3
end

sphere_vol (generic function with 1 method)

In [78]:
typeof(sphere_vol)

#sphere_vol

In [ ]:
sphere_vol(1)

### Ejemplo : Método de Newton para calcular raices cuadradas (Método Babilónico)

* Para calcular la raiz cuadrada de $S$ un método bastante conocido es el de los Babilonios (derivable del método de newton para buscar ceros). El algoritmo puede ser presentado como un sistema dinámico discreto:
$$x_{n+1}=\frac{1}{2} \left( x_n+\frac{S}{x_n} \right), \hspace{5 pt} \lim_{n\to\infty} x_n\to \sqrt{S}.$$
Donde $x_0$ es una condicion inicial cualquiera, finita y acotada. Típicamente uno escoge una buena condicion inicial para que el metodo converja rapido.

__Nota:__ Por favor entiendan que para encontrar la fórmula anterior solo se sustituyó: 
$$f(x)=x^2-S \hspace{10 pt} \text{y} \hspace{10 pt} f'(x)=2x.$$

In [79]:
"""
Esta función calcula la raiz cuadrada
"""
function sqrt_root(S)
    x=S/2;
    for i in 1:20
       x=0.5(x+S/x)
    end
    return x
end

sqrt_root

In [80]:
sqrt_root(2)

1.414213562373095

In [81]:
sqrt(2)

1.4142135623730951

* Podemos mirar la documentación que agregamos a nuestra función como cualquier otra función de Julia:

In [82]:
?sqrt_root

search:



Esta función calcula la raiz cuadrada


__Ejercicio 1:__ Crear una rutina que calcule las raices de la siguiente ecuación trascendental: 
$$x \tan(x)=\sqrt{A-x^2},$$
esta ecuación tiene interes en la física cuántica de particulas en una dimensión, en particular, sus soluciones estan directamente relacionadas con las eigenenergias del _pozo finito cuadrado_, y el número de soluciones posibles es precisamente el número de estados _ligados_ que caben en el pozo.

__Nota:__ Usar varias condiciones iniciales $x_0$.

__Anuncio:__ En la siguiente clase terminamos el ejercicio anterior y continuamos con el siguiente. No hubo tarea en esta clase.

__Ejercicio 2:__ Una vez concluido este ejercicio, deberán crear un repositorio en _github.com_ llamado "Fisica\_Computacional\_Apellido1\_Apellido2", github les dara la opción de inicializarlo con el archivo de _markdown_ _README.md_, github usa este archivo para presenar brevemente de que se trata el repositorio recién creado. 

1. En ese archivo pongan simplemente "Tareas de Su_Nombre".

2. Una vez creado el repositorio deberán hacer un git clone en la maquina virtual que proporciona JuliaBox o en su computadora según les convenga.

3. Para hacer su primera contribución al repositorio, copiaran el notebook del ejercicio anterior dentro de la carpeta del repositorio.

4. Hecho esto hagan `git status` para ver que ha cambiado en nuestro repositorio.

5. Luego, con `git add nombre_del_archivo` agregarán el notebook recién creado para que git siga los cambios. Recuerden que se pueden agregar mas archivos según sus necesidades, digamos `git add nombre_del_archivo1 nombre_del_archivo2`

6. Luego, con `git commit -m'primer ejercicio de git'` creamos un _nodo_ en la carpeta .git, la cual git usa para darle seguimiento a nuestros archivos. Un _nodo_ constituye un _estado_ de nuestro repositorio, estos son usados para registrar los cambios importantes y tener puntos de control si tenemos que regresar a recuperar algo.

7. Finalmente, con `git push` subimos los cambios del repositorio local al remoto, es decir, ahora el repositorio remoto, en _github_ cuenta con el _estado_ más actual de nuestro trabajo. `git push` es lo mismo que `git push origin master` para nuestro caso (el más simple), `origin` es la etiqueta que tiene por defecto la dirección del repositorio remoto, mientras que `master` es la _rama_ del repositorio. Para hacer las cosas simples de momento solo trabajaremos en una rama, es decir, no habrá nodos que se dividan en dos caminos distintos (o más) del repositorio.

## Mecanismo para entregar las tareas de programación

Una vez hecha una tarea, o un ejercicio en clase, se deberán seguir los pasos anteriores para subir sus tareas a su repositorio remoto. Sin embargo, para que los ayudantes sepan cuando revisar si ya hay algo mas dentro, deberán enviarle un correo al ayudante _que toque_ (yo les dire quién) con el asunto #Tarea_Apellidos, y en el cuerpo del correo deberá ir el _enlace_ de su repositorio.